name: Ad hoc pipeline
on:
  workflow_dispatch:
    inputs:
      is_full_refresh:
        description: 'Flag indicating if a full-refresh should happen'
        required: true 
        default: 'false'
      scan_dataset:
        description: 'Indicate what dataset you want to scan with soda'
        required: true
        default: 'staging'
      scan_tables:
        description: 'Indicate what tables you want to scan with soda. If it is more than one, provide table values separated by commas'
        required: false
        default: 'stg_tags'

jobs:
  ad_hoc:
    name: Ad hoc job
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.7 ]

# change the host and token to ACC if we want to move ACC to non-prd consumer zone
    env: 
      BQ_ACCESS: ${{ secrets.BIGQUERY_SERVICE_ACCOUNT }}

    steps: 
      - uses: actions/checkout@v1

      - name: Materialize key file in runner
        run: |
          echo $BQ_ACCESS > /home/runner/work/bq_keys.json

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install pip
        run: |
          python -m pip install --upgrade pip

      - name: Install python dependencies
        run: | 
          pip install -r $GITHUB_WORKSPACE/requirements.txt

      - name: Run dbt
        run: |
          if [ ${{ github.event.inputs.is_full_refresh }} = "false" ]; then dbt run --profiles-dir $GITHUB_WORKSPACE/dbt/ --project-dir $GITHUB_WORKSPACE/dbt/; else dbt run --profiles-dir $GITHUB_WORKSPACE/dbt/ --project-dir $GITHUB_WORKSPACE/dbt/ --full-refresh; fi

      - name: Run soda
        run: |
          if [ ${{ github.event.inputs.scan_tables }} = "" ]
          then 
            python $GITHUB_WORKSPACE/soda/trigger_soda.py --dataset ${{ github.event.inputs.scan_dataset }}
          else 
            python $GITHUB_WORKSPACE/soda/trigger_soda.py --dataset ${{ github.event.inputs.scan_dataset }} --tables ${{ github.event.inputs.scan_tables }}
