name: Pipeline
on:
  schedule:
    - cron: '00 12 * * *'

jobs:
  Pipeline:
    name: Pipeline
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.7 ]

# change the host and token to ACC if we want to move ACC to non-prd consumer zone
    env: 
      BQ_ACCESS: ${{ secrets.BIGQUERY_SERVICE_ACCOUNT }}

    steps: 
      - uses: actions/checkout@v1

      - name: Materialize key file in runner
        run: |
          echo $BQ_ACCESS > /home/runner/work/bq_keys.json

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install pip
        run: |
          python -m pip install --upgrade pip

      - name: Install python dependencies
        run: | 
          pip install -r $GITHUB_WORKSPACE/requirements.txt

      - name: Run dbt
        run: |
          dbt deps --profiles-dir $GITHUB_WORKSPACE/dbt/ --project-dir $GITHUB_WORKSPACE/dbt/
          dbt run --profiles-dir $GITHUB_WORKSPACE/dbt/ --project-dir $GITHUB_WORKSPACE/dbt/

      - name: Run soda
        env: 
          API_KEY_ID: ${{ secrets.API_KEY_ID }}
          API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
        run: |
          python $GITHUB_WORKSPACE/soda/trigger_soda.py --dataset staging,intermediate,marts_core,marts_analytics
