name: test
on:
  push:
    branches:
      - work_on_pipeline

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.7 ]

# change the host and token to ACC if we want to move ACC to non-prd consumer zone
    env: 
      BQ_ACCESS: ${{ secrets.BIGQUERY_SERVICE_ACCOUNT }}

    steps: 
      - uses: actions/checkout@v1

      - name: Materialize key file in runner
        run: |
          echo $BQ_ACCESS > /home/runner/work/bq_keys.json

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install pip
        run: |
          python -m pip install --upgrade pip

      - name: Install python dependencies
        run: | 
          pip install -r $GITHUB_WORKSPACE/requirements.txt

      - name: Run dbt
        run: |
          dbt run --profiles-dir $GITHUB_WORKSPACE
